require ("config.setup.telescope")
require ("config.setup.treesitter")
require ("config.setup.lsp")
require ("config.setup.completion")
require ("config.setup.undotree")
require ("config.setup.trouble")
